// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABfDWTQSSbvkqgsGEIDkoqXmbLe4HIMLU',
    appId: '1:345367800141:web:7f66e0a74168c6a1adaf04',
    messagingSenderId: '345367800141',
    projectId: 'dev-flutter-7f22f',
    authDomain: 'dev-flutter-7f22f.firebaseapp.com',
    storageBucket: 'dev-flutter-7f22f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG848pdDzyOhS9_FZU52zOc4y8pt4Git8',
    appId: '1:345367800141:android:1c4be63703fdb035adaf04',
    messagingSenderId: '345367800141',
    projectId: 'dev-flutter-7f22f',
    storageBucket: 'dev-flutter-7f22f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkTm5XHmpynKq52T1aELaSn9pHcElYmbE',
    appId: '1:345367800141:ios:7277a7f0eb3a5e76adaf04',
    messagingSenderId: '345367800141',
    projectId: 'dev-flutter-7f22f',
    storageBucket: 'dev-flutter-7f22f.appspot.com',
    iosBundleId: 'com.example.buy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkTm5XHmpynKq52T1aELaSn9pHcElYmbE',
    appId: '1:345367800141:ios:89ead60bd6c9e9f1adaf04',
    messagingSenderId: '345367800141',
    projectId: 'dev-flutter-7f22f',
    storageBucket: 'dev-flutter-7f22f.appspot.com',
    iosBundleId: 'com.example.buy.RunnerTests',
  );
}
